CREATE TABLE IF NOT EXISTS Llibre (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titol VARCHAR(255) NOT NULL,
    autor VARCHAR(255) NOT NULL,
    editorial VARCHAR(255) NOT NULL,
    datapublicacio DATE NOT NULL,
    tematica VARCHAR(255) NOT NULL,
    isbn VARCHAR(20) NOT NULL UNIQUE
);